### PR TITLE
Drug data

### PR DESCRIPTION
**Pull request by aditnath**
Initial commit of the drug dataset for viewing on the cell feature explorer

### CODE REVIEW

**Comment by meganrm** [comment]
you actually want to make this PR to https://github.com/allen-cell-animated/cell-feature-data

**Comment by toloudis** [comment]
@aditnath Please do this pr on allen-cell-animated/cell-feature-data and set the base (target) branch to allen-cell-animated/cell-feature-data/main .  For some reason, because it was originally forked from here, PRs get targeted back here by default.

@meganrm Do you know if there is a way to "detach" allen-cell-animated/cell-feature-data from AllenInstitute/cell-feature-data so this stops happening?

**Comment by meganrm** [comment]
> @aditnath Please do this pr on allen-cell-animated/cell-feature-data and set the base (target) branch to allen-cell-animated/cell-feature-data/main . For some reason, because it was originally forked from here, PRs get targeted back here by default.
> 
> @meganrm Do you know if there is a way to "detach" allen-cell-animated/cell-feature-data from AllenInstitute/cell-feature-data so this stops happening?

I'm not sure, but I guess another question would be do we want to just merge our fork in and use the `AllenInstitute/cell-feature-data`? Originally it was because the site was actually loading the data directly from the GitHub repo so I forked it to make sure we didn't break the production site, but that's not the case anymore

**Comment by toloudis** [comment]
I don't really mind either way but it gets confusing using a mixture of repos from various different orgs.  I wish github just had a "set default target branch for PRs" and then we'd be done.

**Comment by aditnath** [comment]
just made a new PR: https://github.com/allen-cell-animated/cell-feature-data/pull/68, let me know if that is correct and whether I can delete this PR

**Comment by toloudis** [comment]
> just made a new PR: [allen-cell-animated#68](https://github.com/allen-cell-animated/cell-feature-data/pull/68), let me know if that is correct and whether I can delete this PR

Much better, thank you!

**Pull request closed without merging**
